version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: papeleria_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-papeleria}
      POSTGRES_PASSWORD: ${DB_PASS:-papeleria123}
      POSTGRES_DB: ${DB_NAME:-papeleria}
    ports:
      - "55432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: papeleria_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@papeleria.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5055:80"
    depends_on:
      - postgres

volumes:
  pg_data:
